# Generated by Django 4.2.3 on 2023-10-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Status', models.BooleanField(default=False)),
                ('Create_Time', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Uploads/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.category')),
            ],
        ),
    ]
