# Generated by Django 4.2.3 on 2023-10-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcreate',
            name='Trending',
            field=models.BooleanField(default=False, help_text='0-False ,1-True'),
        ),
    ]
