# Generated by Django 4.2.3 on 2023-10-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_blogcreate_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcreate',
            name='Status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='blogcreate',
            name='Trending',
            field=models.BooleanField(blank=True, default=False, help_text='0-False ,1-True', null=True),
        ),
    ]
