# Generated by Django 4.2.3 on 2023-10-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_blogcreate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcreate',
            name='Status',
            field=models.BooleanField(help_text='0-Show ,1-Hide', null=True),
        ),
        migrations.AlterField(
            model_name='blogcreate',
            name='Trending',
            field=models.BooleanField(help_text='0-False ,1-True', null=True),
        ),
    ]
