# Generated by Django 4.2.3 on 2023-10-10 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_blogcreate_status_alter_blogcreate_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcreate',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='API.category'),
        ),
        migrations.AlterField(
            model_name='blogcreate',
            name='Status',
            field=models.BooleanField(default=True, help_text='0-Show ,1-Hide', null=True),
        ),
        migrations.AlterField(
            model_name='blogcreate',
            name='Trending',
            field=models.BooleanField(default=False, help_text='0-False ,1-True', null=True),
        ),
    ]
