# Generated by Django 4.2.3 on 2023-10-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_blogcreate_key_word_blogcreate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcreate',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
